# Generated by Django 5.0.6 on 2024-09-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_fixture_gameweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='away_score',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home_score',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
