# Generated by Django 5.0.6 on 2024-09-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_fixture_away_score_alter_fixture_home_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('goals', models.IntegerField(null=True)),
                ('team_name', models.IntegerField(null=True)),
            ],
        ),
    ]
