# Generated by Django 5.0.6 on 2024-09-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_statboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statboard',
            name='team_name',
            field=models.CharField(max_length=50),
        ),
    ]
