# Generated by Django 5.0.6 on 2024-09-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_statboard_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='statboard',
            name='assists',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statboard',
            name='clean_sheets',
            field=models.IntegerField(null=True),
        ),
    ]
