# Generated by Django 5.0.6 on 2024-09-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_statboard_assists_statboard_clean_sheets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_scorer', models.CharField(max_length=50, null=True)),
                ('away_scorer', models.CharField(max_length=50, null=True)),
                ('scoringtime', models.CharField(max_length=50, null=True)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fixture')),
            ],
        ),
    ]
