# Generated by Django 5.0.6 on 2024-09-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_clubs_players_delete_matchdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clubs',
            new_name='Club',
        ),
        migrations.RenameModel(
            old_name='Players',
            new_name='Squad',
        ),
    ]
