# Generated by Django 5.0.6 on 2024-09-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_clubs_club_rename_players_squad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_logo',
            field=models.ImageField(null=True, upload_to='logo/'),
        ),
    ]
